---
version: '2'
services:
  mysql-server:
    image: mysql/mysql-server
    privileged: true
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_ONETIME_PASSWORD: yes
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: 