---
gitlab-server:
  ports:
  - ${ssh_port}:22/tcp
  labels:
    io.rancher.sidekicks: gitlab-data
    rap.host: "${gitlab_hostname}"
    rap.port: 80
    rap.proto: http
    rap.le_host: "${gitlab_hostname}"
    rap.le_email: "divo@divo.net.pl"
  hostname: ${gitlab_hostname}
  image: gitlab/gitlab-ce:latest
  volumes_from:
  - gitlab-data
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url '${gitlab_omnipus_prefix}${gitlab_hostname}'
      unicorn['worker_processes'] = ${WORKERS}
      unicorn['worker_timeout'] = ${TIMEOUT}
      gitlab_rails['gitlab_email_enabled'] = false
      gitlab_rails['env'] = {"SIDEKIQ_MEMORY_KILLER_MAX_RSS" => "716800"}
      sidekiq['concurrency'] = ${CONCURRENCY}

gitlab-data:
  labels:
    io.rancher.container.start_once: 'true'
  net: none
  entrypoint:
    - /bin/true
  image: busybox
  volumes:
  - /data/gitlab/etc/:/etc/gitlab
  - /data/gitlab/log/:/var/log/gitlab
  - /data/gitlab/opt/:/var/opt/gitlab