---
gitlab-server:
  ports:
    - ${ssh_port}:22/tcp
  labels:
    rap.host: "${gitlab_hostname}"
    rap.port: 80
    rap.proto: http
    rap.le_host: "${gitlab_hostname}"
    rap.le_email: "divo@divo.net.pl"
  hostname: ${gitlab_hostname}
  image: gitlab/gitlab-ce:latest
  volumes:
    - gitlab-data-etc:/etc/gitlab
    - gitlab-data-log:/var/log/gitlab
    - gitlab-data-opt:/var/opt/gitlab
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'https://${gitlab_hostname}'
      unicorn['worker_processes'] = ${WORKERS}
      unicorn['worker_timeout'] = ${TIMEOUT}
      gitlab_rails['gitlab_email_enabled'] = false
      gitlab_rails['env'] = {"SIDEKIQ_MEMORY_KILLER_MAX_RSS" => "716800"}
      sidekiq['concurrency'] = ${CONCURRENCY}

volumes:
  gitlab-data-etc: {}
  gitlab-data-log: {}
  gitlab-data-opt: {}