---
version: '2'
services:
  gitlab-server:
    image: gitlab/gitlab-ce:latest
    ports:
      - ${ssh_port}:22/tcp
    volumes:
      - config-gitlab:/etc/gitlab
      - data-gitlab:/var/log/gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://${hostname}'
        unicorn['worker_processes'] = ${WORKERS}
        unicorn['worker_timeout'] = ${TIMEOUT}
        gitlab_rails['gitlab_email_enabled'] = false
        gitlab_rails['env'] = {"SIDEKIQ_MEMORY_KILLER_MAX_RSS" => "716800"}
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "poczta.divo.net.pl"
        gitlab_rails['smtp_port'] = 465
        gitlab_rails['smtp_user_name'] = "${smtp_user}"
        gitlab_rails['smtp_password'] = "${smtp_password}"
        gitlab_rails['smtp_domain'] = "${hostname}"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_openssl_verify_mode'] = 'peer'
        gitlab_rails['gitlab_email_from'] = '${smtp_user}'
        gitlab_rails['gitlab_email_reply_to'] = 'noreply@${hostname}'
        sidekiq['concurrency'] = ${CONCURRENCY}

volumes:
  config-gitlab:
    driver: ${VOLUME_DRIVER}
    name: config-gitlab
  data-gitlab:
    driver: ${VOLUME_DRIVER}
    name: data-gitlab