---
version: '2'

services:

  lempemp:
    labels:
      io.rancher.container.pull_image: always
      rap.host: "${DOMAIN}"
      rap.port: 80
      rap.proto: http
      rap.le_host: "${DOMAIN}"
      rap.le_email: "divo@divo.net.pl"
    image: stenote/docker-lemp
    volumes_from:
    - lemp-data

  lemp-data:
    labels:
      io.rancher.container.start_once: 'true'
    entrypoint:
      - /bin/true
    image: busybox
    volumes:
      - /data/www/${DOMAIN}/:/var/www/