version: '2'

services:
  bitbucket:
    image: atlassian/bitbucket-server:latest
    volumes:
      - bitbucket-volume:/var/atlassian/application-data/bitbucket
    labels:
      io.rancher.container.hostname_override: container_name

volumes:
  bitbucket-volume:
