---
version: '2'

services:

  wordpress:
    labels:
      io.rancher.sidekicks: mysql
      io.rancher.container.pull_image: always
      rap.host: "${DOMAIN}"
      rap.port: 443
      rap.proto: https
      rap.le_host: "${DOMAIN}"
      rap.le_email: "divo@divo.net.pl"
    image: wordpress
    links:
      - mysql:mysql
    volumes:
      - /data.secure/var/www/${DOMAIN}/:/var/www/html/
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: "SXykY4oC5fLnM89eY6XjGn5kQAsn48"

  mysql:
    image: mariadb
    volumes:
      - /data.secure/mysql/${DOMAIN}/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "SXykY4oC5fLnM89eY6XjGn5kQAsn48"