---
wordpress:
  labels:
    io.rancher.container.pull_image: always
    rap.host: "${DOMAIN}"
    rap.port: 443
    rap.proto: https
    rap.le_host: "${DOMAIN}"
    rap.le_email: "divo@divo.net.pl"
  image: wordpress
  links:
    - db:mysql
  volumes:
    - /data.secure/var/www/${DOMAIN}/:/var/www/html/

db:
  image: mariadb
  labels:
    io.rancher.container.start_once: 'true'
  net: none
  volumes:
    - /data.secure/mysql/${DOMAIN}/:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: "wudj6es3#$%yd31@"