---
version: '2'
services:
  wordpress:
    labels:
      rap.host: "${DOMAIN}"
      rap.port: 80
      rap.proto: http
      rap.le_host: "${DOMAIN}"
      rap.le_email: "divo@divo.net.pl"
    image: wordpress
    links:
      - mysql
    volumes:
      - wordpress-data:/var/www/html/
    environment:
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}

  mysql:
    image: mariadb
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

volumes:
  wordpress-data: 
  mysql-data: 