---
version: '2'
services:
  wordpress:
    labels:
      io.rancher.sidekicks: wordpress-data, db
      io.rancher.container.pull_image: always
      rap.host: "${DOMAIN}"
      rap.port: 80
      rap.proto: http
      rap.le_host: "${DOMAIN}"
      rap.le_email: "divo@divo.net.pl"
    image: wordpress
    links:
      - db:mysql
    volumes_from:
      - wordpress-data
    environment:
      WORDPRESS_DB_PASSWORD: "SXykY4oC5fLnM89eY6XjGn5kQAsn48"
    depends_on:
      - wordpress-data
      - db

  db:
    image: mariadb
    volumes_from:
      - db-data
    environment:
      MYSQL_ROOT_PASSWORD: "SXykY4oC5fLnM89eY6XjGn5kQAsn48"

  db-data:
    labels:
      io.rancher.container.start_once: 'true'
    entrypoint:
      - /bin/true
    image: busybox
    volumes:
      - /data/mysql/${DOMAIN}/:/var/lib/mysql

  wordpress-data:
    labels:
      io.rancher.container.start_once: 'true'
    entrypoint:
      - /bin/true
    image: busybox
    volumes:
      - /data/www/${DOMAIN}/:/var/www/html/