---
version: '2'
services:
  docker-samba:
    image: divo/samba
    privileged: true
    restart: always
    environment:
      SAMBA_ARGS: ${SAMBA_ARGS}
    volumes:
      - samba-data:/srv/shares/home/
      - /data.secure/nfs/public:/srv/shares/public/

volumes:
  samba-data: