---
samba-data:
  labels:
    io.rancher.container.start_once: 'true'
  net: none
  entrypoint:
    - /bin/true
  image: busybox
  volumes:
    - /data.secure/samba/srv/shares/public:/srv/shares/public/
    - /data.secure/samba/srv/shares/home:/srv/shares/home/

docker-samba:
  image: divo/samba
  privileged: true
  restart: always
  expose:
    - 137
    - 138
    - 139
    - 445
  labels:
    io.rancher.sidekicks: samba-data
    io.rancher.container.pull_image: always
  volumes_from:
    - samba-data
  entrypoint: /usr/bin/start.sh $SAMBA_ARGS
#  command: /usr/bin/samba.sh $SAMBA_ARGS
