---
docker-samba:
  image: divo/samba
  privileged: true
  restart: always
  expose:
    - 137
    - 138
    - 139
    - 445
  volumes:
    - /data.secure/samba/srv/:/srv
  entrypoint: /usr/bin/samba.sh
  command: $SAMBA_ARGS
