---
docker-nfs:
  image: dperson/samba
  privileged: true
  restart: always
  volumes:
  - /data:/srv
  entrypoint: /usr/bin/samba.sh -u "divo;I9loter653ck45n645n546un57o80z79q0eb6v;10001;samba" -s "divo;/srv/divo;no;no;no;divo"