---
samba-data:
  labels:
    io.rancher.container.start_once: 'true'
  net: none
  entrypoint:
    - /bin/true
  image: busybox
  volumes:
#    - /data.secure/nfs/public:/srv/shares/public/
    - /data.secure/samba/srv/shares/home:/srv/shares/home/
#    - /srv:/srv/shares/public/
#    - /srv:/srv/shares/home/

docker-samba:
  image: divo/samba
  privileged: true
  restart: always
  ports:
    - 137:137/udp
    - 138:138/udp
    - 139:139/tcp
    - 445:445/tcp
  environment:
    SAMBA_ARGS: ${SAMBA_ARGS}
  labels:
    io.rancher.sidekicks: samba-data
    io.rancher.container.pull_image: always
  volumes_from:
    - samba-data
#  entrypoint: /usr/bin/start.sh $SAMBA_ARGS
#  command: /usr/bin/samba.sh $SAMBA_ARGS
