---
samba-data:
  labels:
    io.rancher.container.start_once: 'true'
  net: none
  entrypoint:
    - /bin/true
  image: busybox
  volumes:
    - /data/:/srv/data
    - /data.secure/:/srv/secure
    - /data.secure/nfs/public:/srv/shares/public/
    - /data.secure/samba/srv/shares/home:/srv/shares/home/

docker-samba:
  image: divo/samba
  privileged: true
  restart: always
  environment:
    SAMBA_ARGS: ${SAMBA_ARGS}
  labels:
    io.rancher.sidekicks: samba-data
    io.rancher.container.pull_image: always
  volumes_from:
    - samba-data
