---
version: '2'
services:
  modx-web:
    labels:
      rap.host: "${DOMAIN}"
      rap.port: 80
      rap.proto: http
      rap.le_host: "${DOMAIN}"
      rap.le_email: "divo@divo.net.pl"
    image: modx
    links:
      - mysql
    volumes:
      - modx-data:/usr/src/modx/
    depends_on:
      - mysql

  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: iqtLiJbPVf7DmjaWMME5RPaWphaUCUp
    command: mysqld --sql-mode=NO_ENGINE_SUBSTITUTION

volumes:
  modx-data