---
version: '2'

services:
  modx-web:
    labels:
      io.rancher.sidekicks: modx-db
      io.rancher.container.pull_image: always
      rap.host: "${DOMAIN}"
      rap.port: 80
      rap.proto: http
      rap.le_host: "${DOMAIN}"
      rap.le_email: "divo@divo.net.pl"
    image: modx
    links:
      - modx-db:mysql
    volumes_from:
      - modx-web-data
    depends_on:
      - modx-db

  modx-db:
    image: mariadb
    volumes_from:
      - modx-db-data
    environment:
      MYSQL_ROOT_PASSWORD: example
    command: mysqld --sql-mode=NO_ENGINE_SUBSTITUTION

  modx-web-data:
    labels:
      io.rancher.container.start_once: 'true'
    entrypoint:
      - /bin/true
    image: busybox
    volumes:
      - /data/modx/www/${DOMAIN}/:/usr/src/modx/

  modx-db-data:
    labels:
      io.rancher.container.start_once: 'true'
    entrypoint:
      - /bin/true
    image: busybox
    volumes:
      - /data/modx/mysql/${DOMAIN}/:/var/lib/mysql