---
name: mysql
version: 0.5
description: |
    MYSQL
    Aby dodać hasło trzeba wejść do shell kontenera
    zalogować się do mysql (jednorazowe hasło w logu)
    oraz wykonać:
    ALTER USER root IDENTIFIED BY 'my-secret-pw';
category: sql
maintainer: divo
license: license
projectURL: https://mysql.com/