---
version: '2'

services:
  postgresql:
    restart: always
    image: sameersbn/postgresql:latest
    environment:
    - DB_USER=nextcloud
    - DB_PASS=password
    - DB_NAME=nextcloud
    volumes:
    - /data/nextcloud/postgresql:/var/lib/postgresql

  nextcloud:
    restart: always
    image: sameersbn/nextcloud:latest
    command: app:nextcloud
    environment:
    - DEBUG=true
    - TZ=Europe/Warsaw

    - DB_TYPE=pgsql
    - DB_HOST=postgresql
    - DB_USER=nextcloud
    - DB_PASS=password
    - DB_NAME=nextcloud

    - NEXTCLOUD_URL=http://nc.divo.net.pl

    - NEXTCLOUD_ADMIN_USER=
    - NEXTCLOUD_ADMIN_PASSWORD=

    - NEXTCLOUD_UPLOAD_MAX_FILESIZE=4G
    - NEXTCLOUD_MAX_FILE_UPLOADS=20

    - NEXTCLOUD_BACKUPS_EXPIRY=0
    depends_on:
    - postgresql
    volumes:
    - /data/nextcloud/nextcloud:/var/lib/nextcloud

  nginx:
    restart: always
    image: sameersbn/nextcloud:latest
    command: app:nginx
    labels:
      rap.host: "nc.divo.net.pl"
      rap.port: 80
      rap.proto: http
      rap.le_host: "nc.divo.net.pl"
      rap.le_email: "divo@divo.net.pl"
    environment:
    - NEXTCLOUD_PHP_FPM_HOST=nextcloud
    - NEXTCLOUD_PHP_FPM_PORT=9000
    depends_on:
    - nextcloud