---
version: '2'

services:
  postgresql:
    restart: always
    image: sameersbn/postgresql:9.6-2
    environment:
    - DB_USER=nextcloud
    - DB_PASS=password
    - DB_NAME=nextcloud_db
    volumes:
    - /data.secure/nextcloud/postgresql:/var/lib/postgresql

  nextcloud:
    restart: always
    image: sameersbn/nextcloud:11.0.1
    command: app:nextcloud
    environment:
    - DEBUG=false
    - TZ=Europe/Warsaw

    - DB_TYPE=pgsql
    - DB_HOST=postgresql
    - DB_USER=nextcloud
    - DB_PASS=password
    - DB_NAME=nextcloud_db

    - NEXTCLOUD_URL=http://cloud.example.com:10080

    - NEXTCLOUD_ADMIN_USER=
    - NEXTCLOUD_ADMIN_PASSWORD=

    - NEXTCLOUD_UPLOAD_MAX_FILESIZE=4G
    - NEXTCLOUD_MAX_FILE_UPLOADS=20

    - NEXTCLOUD_BACKUPS_EXPIRY=0
    depends_on:
    - postgresql
    volumes:
    - /data.secure/nextcloud/nextcloud:/var/lib/nextcloud

  nginx:
    restart: always
    image: sameersbn/nextcloud:11.0.1
    command: app:nginx
    labels:
      io.rancher.container.pull_image: always
      rap.host: "nc.divo.net.pl"
      rap.port: 80
      rap.proto: http
    environment:
    - NEXTCLOUD_PHP_FPM_HOST=nextcloud
    - NEXTCLOUD_PHP_FPM_PORT=9000
    depends_on:
    - nextcloud