---
version: '2'
services:
  openvpn-server:
    ports:
      - 1194:1194
    environment:
      AUTH_METHOD: httpbasic
      CERT_COUNTRY: ${CERT_COUNTRY}
      CERT_PROVINCE: ${CERT_PROVINCE}
      CERT_CITY: ${CERT_CITY}
      CERT_ORG: ${CERT_ORG}
      CERT_EMAIL: ${CERT_EMAIL}
      CERT_OU: ${CERT_OU}
      REMOTE_IP: ${REMOTE_IP}
      REMOTE_PORT: ${REMOTE_PORT}
      VPNPOOL_NETWORK: ${VPNPOOL_NETWORK}
      VPNPOOL_CIDR: ${VPNPOOL_CIDR}
      OPENVPN_EXTRACONF: ${OPENVPN_EXTRACONF}
      ROUTE_NETWORK: ${ROUTE_NETWORK}
      ROUTE_CIDR: ${ROUTE_CIDR}
      EASYRSA_KEY_SIZE: ${DHPARAM_KEY}
    labels:
      io.rancher.container.pull_image: always
    image: divo/openvpn
    volumes:
      - openvpn-data:/etc/openvpn/

volumes:
  openvpn-data: